version: 2

jobs:
  build:
    working_directory: /build
    docker:
      - image: quay.io/utilitywarehouse/partner-go-build
      - image: mongo:3.6
        command: mongod --port 27017
    steps:
      - checkout:
          path: /build/project
      - run: git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run: git config --global --add url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "git@github.com:"
      - run: cd project
      - run: make install
      - run: make lint
      - run: make test
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: make docker-build-all
      - run: make docker-push-all

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: partner